[runtime]
log_level = "INFO"

[destination.filesystem]
loader_file_format = "parquet"
layout = "{table_name}/ingest_method={ingest_method}/year={year}/month={month}/{file_id}.{ext}"
extra_placeholders = { "ingest_method" = "batch_sync", "year" = "_default", "month" = "_default" }
# bucket_url = "file:///d:/_1.FWG_PARA/1.Projects/dev/dataware_house/data-integration2/app_data/data_lake"

[sources.sapo]
domain = "fwg.mysapogo.com" # Default domain, override with Env Var if needed
request_delay = 2.0 # Wait 1 second between requests
headless = true
login_url = "https://accounts.sapo.vn/login?domain=fwg" # cấu hình nếu muốn Overview

[sources.sapo.login_selectors]
username = "#pos-login-form #username"
password = "#pos-login-form #password"
submit = "#pos-login-form button.btn-login"

[sources.sapo_webhook_source]
worker_url = "https://webhook-receiver.admin-1d2.workers.dev/"

[sources.spreadsheet_url]
marketing_spend = "https://docs.google.com/spreadsheets/d/1wQpT4lCZWrPE7fnbRNTKiNDRFzVT2u_WhN-9uY9u3lc/edit?usp=sharing"
targets = "https://docs.google.com/spreadsheets/d/1ZHt2iAD88OGgSRopVOkqEgusja-JpP4XqtiH4anhax4/edit?usp=sharing"

[sources.facebook_ads]
access_token = "REPLACE_ME_OR_SET_ENV_VAR" # Required if not in environment
account_id = "REPLACE_ME" # Used if running single account mode

[sources.facebook_messenger]
page_access_token = "REPLACE_ME_OR_SET_ENV_VAR" # Required if not in environment

[sources.shopee]
input_dir = "app_data/input_source/shopee"
file_pattern = "Income.*.xlsx"

[sources.misa_amis]
input_dir = "app_data/input_source/misa-amis"
file_pattern = "So_chi_tiet_ban_hang_*.xlsx"
