[runtime]
log_level = "INFO"

[destination.filesystem]
loader_file_format = "parquet"

[sources.sapo]
domain = "fwg.mysapogo.com" # Default domain, override with Env Var if needed
request_delay = 2.0
headless = true

[sources.spreadsheet_url]
marketing_spend = "https://docs.google.com/spreadsheets/d/1wQpT4lCZWrPE7fnbRNTKiNDRFzVT2u_WhN-9uY9u3lc/edit?usp=sharing"
targets = "https://docs.google.com/spreadsheets/d/1ZHt2iAD88OGgSRopVOkqEgusja-JpP4XqtiH4anhax4/edit?usp=sharing"