// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const insertActivity = `-- name: InsertActivity :exec

INSERT INTO crm_activity (
  activity_id, party_id, activity_type, direction, channel,
  subject, body, outcome, related_order_code,
  staff_user_id, occurred_at, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertActivityParams struct {
	ActivityID       string         `json:"activity_id"`
	PartyID          string         `json:"party_id"`
	ActivityType     string         `json:"activity_type"`
	Direction        sql.NullString `json:"direction"`
	Channel          sql.NullString `json:"channel"`
	Subject          sql.NullString `json:"subject"`
	Body             sql.NullString `json:"body"`
	Outcome          sql.NullString `json:"outcome"`
	RelatedOrderCode sql.NullString `json:"related_order_code"`
	StaffUserID      sql.NullString `json:"staff_user_id"`
	OccurredAt       string         `json:"occurred_at"`
	CreatedAt        string         `json:"created_at"`
}

// Activity queries (crm_activity)
func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, insertActivity,
		arg.ActivityID,
		arg.PartyID,
		arg.ActivityType,
		arg.Direction,
		arg.Channel,
		arg.Subject,
		arg.Body,
		arg.Outcome,
		arg.RelatedOrderCode,
		arg.StaffUserID,
		arg.OccurredAt,
		arg.CreatedAt,
	)
	return err
}

const listActivitiesByParty = `-- name: ListActivitiesByParty :many
SELECT
  activity_id, party_id, activity_type, direction, channel,
  subject, body, outcome, related_order_code,
  staff_user_id, occurred_at, created_at
FROM crm_activity
WHERE party_id = ?
ORDER BY occurred_at DESC
`

func (q *Queries) ListActivitiesByParty(ctx context.Context, partyID string) ([]CrmActivity, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesByParty, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmActivity
	for rows.Next() {
		var i CrmActivity
		if err := rows.Scan(
			&i.ActivityID,
			&i.PartyID,
			&i.ActivityType,
			&i.Direction,
			&i.Channel,
			&i.Subject,
			&i.Body,
			&i.Outcome,
			&i.RelatedOrderCode,
			&i.StaffUserID,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
