// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_user_queries.sql

package sqlcgen

import (
	"context"
)

const getAppUserByEmail = `-- name: GetAppUserByEmail :one
SELECT user_id, staff_id, email, full_name, role, is_active, created_at, updated_at
FROM crm_app_user
WHERE email = ?
LIMIT 1
`

func (q *Queries) GetAppUserByEmail(ctx context.Context, email string) (CrmAppUser, error) {
	row := q.db.QueryRowContext(ctx, getAppUserByEmail, email)
	var i CrmAppUser
	err := row.Scan(
		&i.UserID,
		&i.StaffID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAppUsers = `-- name: ListActiveAppUsers :many
SELECT user_id, staff_id, email, full_name, role, is_active, created_at, updated_at
FROM crm_app_user
WHERE is_active = 1
ORDER BY full_name
`

func (q *Queries) ListActiveAppUsers(ctx context.Context) ([]CrmAppUser, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAppUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmAppUser
	for rows.Next() {
		var i CrmAppUser
		if err := rows.Scan(
			&i.UserID,
			&i.StaffID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
