// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaign_queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT
  campaign_id, name, objective, channel, segment_id, status, scheduled_at, created_by, created_at, updated_at
FROM crm_campaign
WHERE campaign_id = ?
`

func (q *Queries) GetCampaignByID(ctx context.Context, campaignID string) (CrmCampaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByID, campaignID)
	var i CrmCampaign
	err := row.Scan(
		&i.CampaignID,
		&i.Name,
		&i.Objective,
		&i.Channel,
		&i.SegmentID,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignTarget = `-- name: GetCampaignTarget :one
SELECT
  campaign_id, party_id, status, assigned_user_id, last_touch_at,
  converted_order_code, converted_revenue_vnd, converted_at
FROM crm_campaign_target
WHERE campaign_id = ? AND party_id = ?
`

type GetCampaignTargetParams struct {
	CampaignID string `json:"campaign_id"`
	PartyID    string `json:"party_id"`
}

func (q *Queries) GetCampaignTarget(ctx context.Context, arg GetCampaignTargetParams) (CrmCampaignTarget, error) {
	row := q.db.QueryRowContext(ctx, getCampaignTarget, arg.CampaignID, arg.PartyID)
	var i CrmCampaignTarget
	err := row.Scan(
		&i.CampaignID,
		&i.PartyID,
		&i.Status,
		&i.AssignedUserID,
		&i.LastTouchAt,
		&i.ConvertedOrderCode,
		&i.ConvertedRevenueVnd,
		&i.ConvertedAt,
	)
	return i, err
}

const insertCampaign = `-- name: InsertCampaign :exec

INSERT INTO crm_campaign (
  campaign_id, name, objective, channel, segment_id, status, scheduled_at, created_by, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCampaignParams struct {
	CampaignID  string         `json:"campaign_id"`
	Name        string         `json:"name"`
	Objective   string         `json:"objective"`
	Channel     sql.NullString `json:"channel"`
	SegmentID   sql.NullString `json:"segment_id"`
	Status      string         `json:"status"`
	ScheduledAt sql.NullString `json:"scheduled_at"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

// Campaign queries (crm_campaign, crm_campaign_target)
func (q *Queries) InsertCampaign(ctx context.Context, arg InsertCampaignParams) error {
	_, err := q.db.ExecContext(ctx, insertCampaign,
		arg.CampaignID,
		arg.Name,
		arg.Objective,
		arg.Channel,
		arg.SegmentID,
		arg.Status,
		arg.ScheduledAt,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listCampaignTargets = `-- name: ListCampaignTargets :many
SELECT
  campaign_id, party_id, status, assigned_user_id, last_touch_at,
  converted_order_code, converted_revenue_vnd, converted_at
FROM crm_campaign_target
WHERE campaign_id = ?
ORDER BY party_id
`

func (q *Queries) ListCampaignTargets(ctx context.Context, campaignID string) ([]CrmCampaignTarget, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignTargets, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmCampaignTarget
	for rows.Next() {
		var i CrmCampaignTarget
		if err := rows.Scan(
			&i.CampaignID,
			&i.PartyID,
			&i.Status,
			&i.AssignedUserID,
			&i.LastTouchAt,
			&i.ConvertedOrderCode,
			&i.ConvertedRevenueVnd,
			&i.ConvertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignTargetsByStatus = `-- name: ListCampaignTargetsByStatus :many
SELECT
  campaign_id, party_id, status, assigned_user_id, last_touch_at,
  converted_order_code, converted_revenue_vnd, converted_at
FROM crm_campaign_target
WHERE campaign_id = ? AND status = ?
ORDER BY party_id
`

type ListCampaignTargetsByStatusParams struct {
	CampaignID string `json:"campaign_id"`
	Status     string `json:"status"`
}

func (q *Queries) ListCampaignTargetsByStatus(ctx context.Context, arg ListCampaignTargetsByStatusParams) ([]CrmCampaignTarget, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignTargetsByStatus, arg.CampaignID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmCampaignTarget
	for rows.Next() {
		var i CrmCampaignTarget
		if err := rows.Scan(
			&i.CampaignID,
			&i.PartyID,
			&i.Status,
			&i.AssignedUserID,
			&i.LastTouchAt,
			&i.ConvertedOrderCode,
			&i.ConvertedRevenueVnd,
			&i.ConvertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT
  campaign_id, name, objective, channel, segment_id, status, scheduled_at, created_by, created_at, updated_at
FROM crm_campaign
ORDER BY created_at DESC
`

func (q *Queries) ListCampaigns(ctx context.Context) ([]CrmCampaign, error) {
	rows, err := q.db.QueryContext(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmCampaign
	for rows.Next() {
		var i CrmCampaign
		if err := rows.Scan(
			&i.CampaignID,
			&i.Name,
			&i.Objective,
			&i.Channel,
			&i.SegmentID,
			&i.Status,
			&i.ScheduledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :exec
UPDATE crm_campaign
SET
  name         = ?,
  objective    = ?,
  channel      = ?,
  segment_id   = ?,
  status       = ?,
  scheduled_at = ?,
  updated_at   = ?
WHERE campaign_id = ?
`

type UpdateCampaignParams struct {
	Name        string         `json:"name"`
	Objective   string         `json:"objective"`
	Channel     sql.NullString `json:"channel"`
	SegmentID   sql.NullString `json:"segment_id"`
	Status      string         `json:"status"`
	ScheduledAt sql.NullString `json:"scheduled_at"`
	UpdatedAt   string         `json:"updated_at"`
	CampaignID  string         `json:"campaign_id"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) error {
	_, err := q.db.ExecContext(ctx, updateCampaign,
		arg.Name,
		arg.Objective,
		arg.Channel,
		arg.SegmentID,
		arg.Status,
		arg.ScheduledAt,
		arg.UpdatedAt,
		arg.CampaignID,
	)
	return err
}

const updateCampaignTarget = `-- name: UpdateCampaignTarget :exec
UPDATE crm_campaign_target
SET
  status                = ?,
  assigned_user_id      = ?,
  last_touch_at         = ?,
  converted_order_code  = ?,
  converted_revenue_vnd = ?,
  converted_at          = ?
WHERE campaign_id = ? AND party_id = ?
`

type UpdateCampaignTargetParams struct {
	Status              string         `json:"status"`
	AssignedUserID      sql.NullString `json:"assigned_user_id"`
	LastTouchAt         sql.NullString `json:"last_touch_at"`
	ConvertedOrderCode  sql.NullString `json:"converted_order_code"`
	ConvertedRevenueVnd sql.NullInt64  `json:"converted_revenue_vnd"`
	ConvertedAt         sql.NullString `json:"converted_at"`
	CampaignID          string         `json:"campaign_id"`
	PartyID             string         `json:"party_id"`
}

func (q *Queries) UpdateCampaignTarget(ctx context.Context, arg UpdateCampaignTargetParams) error {
	_, err := q.db.ExecContext(ctx, updateCampaignTarget,
		arg.Status,
		arg.AssignedUserID,
		arg.LastTouchAt,
		arg.ConvertedOrderCode,
		arg.ConvertedRevenueVnd,
		arg.ConvertedAt,
		arg.CampaignID,
		arg.PartyID,
	)
	return err
}

const upsertCampaignTarget = `-- name: UpsertCampaignTarget :exec
INSERT INTO crm_campaign_target (
  campaign_id, party_id, status, assigned_user_id, last_touch_at,
  converted_order_code, converted_revenue_vnd, converted_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (campaign_id, party_id) DO NOTHING
`

type UpsertCampaignTargetParams struct {
	CampaignID          string         `json:"campaign_id"`
	PartyID             string         `json:"party_id"`
	Status              string         `json:"status"`
	AssignedUserID      sql.NullString `json:"assigned_user_id"`
	LastTouchAt         sql.NullString `json:"last_touch_at"`
	ConvertedOrderCode  sql.NullString `json:"converted_order_code"`
	ConvertedRevenueVnd sql.NullInt64  `json:"converted_revenue_vnd"`
	ConvertedAt         sql.NullString `json:"converted_at"`
}

func (q *Queries) UpsertCampaignTarget(ctx context.Context, arg UpsertCampaignTargetParams) error {
	_, err := q.db.ExecContext(ctx, upsertCampaignTarget,
		arg.CampaignID,
		arg.PartyID,
		arg.Status,
		arg.AssignedUserID,
		arg.LastTouchAt,
		arg.ConvertedOrderCode,
		arg.ConvertedRevenueVnd,
		arg.ConvertedAt,
	)
	return err
}
