// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getConversationByChannelThread = `-- name: GetConversationByChannelThread :one
SELECT
  conversation_id, party_id, channel, external_thread_id, page_id,
  status, assignee_user_id, last_message_at, unread_count, created_at, updated_at
FROM crm_conversation
WHERE channel = ? AND external_thread_id = ?
`

type GetConversationByChannelThreadParams struct {
	Channel          string `json:"channel"`
	ExternalThreadID string `json:"external_thread_id"`
}

func (q *Queries) GetConversationByChannelThread(ctx context.Context, arg GetConversationByChannelThreadParams) (CrmConversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByChannelThread, arg.Channel, arg.ExternalThreadID)
	var i CrmConversation
	err := row.Scan(
		&i.ConversationID,
		&i.PartyID,
		&i.Channel,
		&i.ExternalThreadID,
		&i.PageID,
		&i.Status,
		&i.AssigneeUserID,
		&i.LastMessageAt,
		&i.UnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT
  conversation_id, party_id, channel, external_thread_id, page_id,
  status, assignee_user_id, last_message_at, unread_count, created_at, updated_at
FROM crm_conversation
WHERE conversation_id = ?
`

func (q *Queries) GetConversationByID(ctx context.Context, conversationID string) (CrmConversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, conversationID)
	var i CrmConversation
	err := row.Scan(
		&i.ConversationID,
		&i.PartyID,
		&i.Channel,
		&i.ExternalThreadID,
		&i.PageID,
		&i.Status,
		&i.AssigneeUserID,
		&i.LastMessageAt,
		&i.UnreadCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO crm_message (
  message_id, conversation_id, external_message_id, direction,
  sender_ref, body, attachments, sent_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (conversation_id, external_message_id) DO NOTHING
RETURNING message_id
`

type InsertMessageParams struct {
	MessageID         string         `json:"message_id"`
	ConversationID    string         `json:"conversation_id"`
	ExternalMessageID sql.NullString `json:"external_message_id"`
	Direction         sql.NullString `json:"direction"`
	SenderRef         sql.NullString `json:"sender_ref"`
	Body              sql.NullString `json:"body"`
	Attachments       sql.NullString `json:"attachments"`
	SentAt            string         `json:"sent_at"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (string, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.MessageID,
		arg.ConversationID,
		arg.ExternalMessageID,
		arg.Direction,
		arg.SenderRef,
		arg.Body,
		arg.Attachments,
		arg.SentAt,
	)
	var message_id string
	err := row.Scan(&message_id)
	return message_id, err
}

const listAllConversations = `-- name: ListAllConversations :many
SELECT
  conversation_id, party_id, channel, external_thread_id, page_id,
  status, assignee_user_id, last_message_at, unread_count, created_at, updated_at
FROM crm_conversation
ORDER BY last_message_at DESC
`

func (q *Queries) ListAllConversations(ctx context.Context) ([]CrmConversation, error) {
	rows, err := q.db.QueryContext(ctx, listAllConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmConversation
	for rows.Next() {
		var i CrmConversation
		if err := rows.Scan(
			&i.ConversationID,
			&i.PartyID,
			&i.Channel,
			&i.ExternalThreadID,
			&i.PageID,
			&i.Status,
			&i.AssigneeUserID,
			&i.LastMessageAt,
			&i.UnreadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByAssignee = `-- name: ListConversationsByAssignee :many
SELECT
  conversation_id, party_id, channel, external_thread_id, page_id,
  status, assignee_user_id, last_message_at, unread_count, created_at, updated_at
FROM crm_conversation
WHERE assignee_user_id = ?
ORDER BY last_message_at DESC
`

func (q *Queries) ListConversationsByAssignee(ctx context.Context, assigneeUserID sql.NullString) ([]CrmConversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsByAssignee, assigneeUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmConversation
	for rows.Next() {
		var i CrmConversation
		if err := rows.Scan(
			&i.ConversationID,
			&i.PartyID,
			&i.Channel,
			&i.ExternalThreadID,
			&i.PageID,
			&i.Status,
			&i.AssigneeUserID,
			&i.LastMessageAt,
			&i.UnreadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByAssigneeAndStatus = `-- name: ListConversationsByAssigneeAndStatus :many
SELECT
  conversation_id, party_id, channel, external_thread_id, page_id,
  status, assignee_user_id, last_message_at, unread_count, created_at, updated_at
FROM crm_conversation
WHERE assignee_user_id = ? AND status = ?
ORDER BY last_message_at DESC
`

type ListConversationsByAssigneeAndStatusParams struct {
	AssigneeUserID sql.NullString `json:"assignee_user_id"`
	Status         string         `json:"status"`
}

func (q *Queries) ListConversationsByAssigneeAndStatus(ctx context.Context, arg ListConversationsByAssigneeAndStatusParams) ([]CrmConversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsByAssigneeAndStatus, arg.AssigneeUserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmConversation
	for rows.Next() {
		var i CrmConversation
		if err := rows.Scan(
			&i.ConversationID,
			&i.PartyID,
			&i.Channel,
			&i.ExternalThreadID,
			&i.PageID,
			&i.Status,
			&i.AssigneeUserID,
			&i.LastMessageAt,
			&i.UnreadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByStatus = `-- name: ListConversationsByStatus :many
SELECT
  conversation_id, party_id, channel, external_thread_id, page_id,
  status, assignee_user_id, last_message_at, unread_count, created_at, updated_at
FROM crm_conversation
WHERE status = ?
ORDER BY last_message_at DESC
`

func (q *Queries) ListConversationsByStatus(ctx context.Context, status string) ([]CrmConversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmConversation
	for rows.Next() {
		var i CrmConversation
		if err := rows.Scan(
			&i.ConversationID,
			&i.PartyID,
			&i.Channel,
			&i.ExternalThreadID,
			&i.PageID,
			&i.Status,
			&i.AssigneeUserID,
			&i.LastMessageAt,
			&i.UnreadCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT
  message_id, conversation_id, external_message_id, direction,
  sender_ref, body, attachments, sent_at
FROM crm_message
WHERE conversation_id = ?
ORDER BY sent_at ASC
`

func (q *Queries) ListMessagesByConversation(ctx context.Context, conversationID string) ([]CrmMessage, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmMessage
	for rows.Next() {
		var i CrmMessage
		if err := rows.Scan(
			&i.MessageID,
			&i.ConversationID,
			&i.ExternalMessageID,
			&i.Direction,
			&i.SenderRef,
			&i.Body,
			&i.Attachments,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversation = `-- name: UpdateConversation :exec
UPDATE crm_conversation
SET
  party_id         = ?,
  status           = ?,
  assignee_user_id = ?,
  last_message_at  = ?,
  unread_count     = ?,
  updated_at       = ?
WHERE conversation_id = ?
`

type UpdateConversationParams struct {
	PartyID        sql.NullString `json:"party_id"`
	Status         string         `json:"status"`
	AssigneeUserID sql.NullString `json:"assignee_user_id"`
	LastMessageAt  sql.NullString `json:"last_message_at"`
	UnreadCount    int64          `json:"unread_count"`
	UpdatedAt      string         `json:"updated_at"`
	ConversationID string         `json:"conversation_id"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) error {
	_, err := q.db.ExecContext(ctx, updateConversation,
		arg.PartyID,
		arg.Status,
		arg.AssigneeUserID,
		arg.LastMessageAt,
		arg.UnreadCount,
		arg.UpdatedAt,
		arg.ConversationID,
	)
	return err
}

const updateConversationOnMessage = `-- name: UpdateConversationOnMessage :exec
UPDATE crm_conversation
SET
  last_message_at = CASE WHEN last_message_at IS NULL OR last_message_at < ? THEN ? ELSE last_message_at END,
  unread_count    = unread_count + ?
WHERE conversation_id = ?
`

type UpdateConversationOnMessageParams struct {
	LastMessageAt   sql.NullString `json:"last_message_at"`
	LastMessageAt_2 sql.NullString `json:"last_message_at_2"`
	UnreadCount     int64          `json:"unread_count"`
	ConversationID  string         `json:"conversation_id"`
}

// Atomically advances last_message_at and increments unread_count by delta.
// Pass delta=1 for inbound messages, delta=0 for echo/outbound.
// Called only when a new message row was actually inserted (idempotency enforced by caller).
func (q *Queries) UpdateConversationOnMessage(ctx context.Context, arg UpdateConversationOnMessageParams) error {
	_, err := q.db.ExecContext(ctx, updateConversationOnMessage,
		arg.LastMessageAt,
		arg.LastMessageAt_2,
		arg.UnreadCount,
		arg.ConversationID,
	)
	return err
}

const upsertConversation = `-- name: UpsertConversation :one

INSERT INTO crm_conversation (
  conversation_id, party_id, channel, external_thread_id, page_id,
  status, assignee_user_id, last_message_at, unread_count, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (channel, external_thread_id) DO NOTHING
RETURNING conversation_id
`

type UpsertConversationParams struct {
	ConversationID   string         `json:"conversation_id"`
	PartyID          sql.NullString `json:"party_id"`
	Channel          string         `json:"channel"`
	ExternalThreadID string         `json:"external_thread_id"`
	PageID           sql.NullString `json:"page_id"`
	Status           string         `json:"status"`
	AssigneeUserID   sql.NullString `json:"assignee_user_id"`
	LastMessageAt    sql.NullString `json:"last_message_at"`
	UnreadCount      int64          `json:"unread_count"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

// Conversation and Message queries (crm_conversation, crm_message)
func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertConversation,
		arg.ConversationID,
		arg.PartyID,
		arg.Channel,
		arg.ExternalThreadID,
		arg.PageID,
		arg.Status,
		arg.AssigneeUserID,
		arg.LastMessageAt,
		arg.UnreadCount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var conversation_id string
	err := row.Scan(&conversation_id)
	return conversation_id, err
}
