// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dedup_queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const dedupCandidateExists = `-- name: DedupCandidateExists :one
-- Only a 'pending' candidate blocks re-detection; merged/rejected pairs can be re-scanned.
SELECT COUNT(*) FROM crm_dedup_candidate
WHERE status = 'pending'
  AND (
    (party_a = ? AND party_b = ?)
    OR
    (party_a = ? AND party_b = ?)
  )
`

type DedupCandidateExistsParams struct {
	PartyA   string `json:"party_a"`
	PartyB   string `json:"party_b"`
	PartyA_2 string `json:"party_a_2"`
	PartyB_2 string `json:"party_b_2"`
}

func (q *Queries) DedupCandidateExists(ctx context.Context, arg DedupCandidateExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dedupCandidateExists,
		arg.PartyA,
		arg.PartyB,
		arg.PartyA_2,
		arg.PartyB_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDedupCandidate = `-- name: GetDedupCandidate :one
SELECT candidate_id, party_a, party_b, match_rule, match_score,
       status, reviewed_by, reviewed_at, created_at
FROM crm_dedup_candidate
WHERE candidate_id = ?
LIMIT 1
`

func (q *Queries) GetDedupCandidate(ctx context.Context, candidateID string) (CrmDedupCandidate, error) {
	row := q.db.QueryRowContext(ctx, getDedupCandidate, candidateID)
	var i CrmDedupCandidate
	err := row.Scan(
		&i.CandidateID,
		&i.PartyA,
		&i.PartyB,
		&i.MatchRule,
		&i.MatchScore,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMergeLog = `-- name: GetMergeLog :one
SELECT merge_id, surviving_party_id, merged_party_id, reason, merged_by, snapshot, merged_at, undone_at
FROM crm_party_merge_log
WHERE merge_id = ?
LIMIT 1
`

func (q *Queries) GetMergeLog(ctx context.Context, mergeID string) (CrmPartyMergeLog, error) {
	row := q.db.QueryRowContext(ctx, getMergeLog, mergeID)
	var i CrmPartyMergeLog
	err := row.Scan(
		&i.MergeID,
		&i.SurvivingPartyID,
		&i.MergedPartyID,
		&i.Reason,
		&i.MergedBy,
		&i.Snapshot,
		&i.MergedAt,
		&i.UndonAt,
	)
	return i, err
}

const insertDedupCandidate = `-- name: InsertDedupCandidate :exec

INSERT INTO crm_dedup_candidate (
  candidate_id, party_a, party_b, match_rule, match_score, status, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertDedupCandidateParams struct {
	CandidateID string  `json:"candidate_id"`
	PartyA      string  `json:"party_a"`
	PartyB      string  `json:"party_b"`
	MatchRule   string  `json:"match_rule"`
	MatchScore  float64 `json:"match_score"`
	Status      string  `json:"status"`
	CreatedAt   string  `json:"created_at"`
}

// Dedup candidate and merge log queries
func (q *Queries) InsertDedupCandidate(ctx context.Context, arg InsertDedupCandidateParams) error {
	_, err := q.db.ExecContext(ctx, insertDedupCandidate,
		arg.CandidateID,
		arg.PartyA,
		arg.PartyB,
		arg.MatchRule,
		arg.MatchScore,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertMergeLog = `-- name: InsertMergeLog :exec

INSERT INTO crm_party_merge_log (
  merge_id, surviving_party_id, merged_party_id, reason, merged_by, snapshot, merged_at
) VALUES (?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
`

type InsertMergeLogParams struct {
	MergeID          string         `json:"merge_id"`
	SurvivingPartyID string         `json:"surviving_party_id"`
	MergedPartyID    string         `json:"merged_party_id"`
	Reason           sql.NullString `json:"reason"`
	MergedBy         sql.NullString `json:"merged_by"`
	Snapshot         sql.NullString `json:"snapshot"`
}

// Merge log queries
func (q *Queries) InsertMergeLog(ctx context.Context, arg InsertMergeLogParams) error {
	_, err := q.db.ExecContext(ctx, insertMergeLog,
		arg.MergeID,
		arg.SurvivingPartyID,
		arg.MergedPartyID,
		arg.Reason,
		arg.MergedBy,
		arg.Snapshot,
	)
	return err
}

const listAllDedupCandidates = `-- name: ListAllDedupCandidates :many
SELECT candidate_id, party_a, party_b, match_rule, match_score,
       status, reviewed_by, reviewed_at, created_at
FROM crm_dedup_candidate
ORDER BY match_score DESC, created_at
`

func (q *Queries) ListAllDedupCandidates(ctx context.Context) ([]CrmDedupCandidate, error) {
	rows, err := q.db.QueryContext(ctx, listAllDedupCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmDedupCandidate
	for rows.Next() {
		var i CrmDedupCandidate
		if err := rows.Scan(
			&i.CandidateID,
			&i.PartyA,
			&i.PartyB,
			&i.MatchRule,
			&i.MatchScore,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDedupCandidatesByStatus = `-- name: ListDedupCandidatesByStatus :many
SELECT candidate_id, party_a, party_b, match_rule, match_score,
       status, reviewed_by, reviewed_at, created_at
FROM crm_dedup_candidate
WHERE status = ?
ORDER BY match_score DESC, created_at
`

func (q *Queries) ListDedupCandidatesByStatus(ctx context.Context, status string) ([]CrmDedupCandidate, error) {
	rows, err := q.db.QueryContext(ctx, listDedupCandidatesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmDedupCandidate
	for rows.Next() {
		var i CrmDedupCandidate
		if err := rows.Scan(
			&i.CandidateID,
			&i.PartyA,
			&i.PartyB,
			&i.MatchRule,
			&i.MatchScore,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDedupCandidateStatus = `-- name: UpdateDedupCandidateStatus :exec
UPDATE crm_dedup_candidate
SET status      = ?,
    reviewed_by = ?,
    reviewed_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE candidate_id = ?
`

type UpdateDedupCandidateStatusParams struct {
	Status      string         `json:"status"`
	ReviewedBy  sql.NullString `json:"reviewed_by"`
	CandidateID string         `json:"candidate_id"`
}

func (q *Queries) UpdateDedupCandidateStatus(ctx context.Context, arg UpdateDedupCandidateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDedupCandidateStatus, arg.Status, arg.ReviewedBy, arg.CandidateID)
	return err
}

const updateMergeLogReason = `-- name: UpdateMergeLogReason :exec
UPDATE crm_party_merge_log
SET reason = ?
WHERE merge_id = ?
`

type UpdateMergeLogReasonParams struct {
	Reason  sql.NullString `json:"reason"`
	MergeID string         `json:"merge_id"`
}

func (q *Queries) UpdateMergeLogReason(ctx context.Context, arg UpdateMergeLogReasonParams) error {
	_, err := q.db.ExecContext(ctx, updateMergeLogReason, arg.Reason, arg.MergeID)
	return err
}
