// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type CrmActivity struct {
	ActivityID       string         `json:"activity_id"`
	PartyID          string         `json:"party_id"`
	ActivityType     string         `json:"activity_type"`
	Direction        sql.NullString `json:"direction"`
	Channel          sql.NullString `json:"channel"`
	Subject          sql.NullString `json:"subject"`
	Body             sql.NullString `json:"body"`
	Outcome          sql.NullString `json:"outcome"`
	RelatedOrderCode sql.NullString `json:"related_order_code"`
	StaffUserID      sql.NullString `json:"staff_user_id"`
	OccurredAt       string         `json:"occurred_at"`
	CreatedAt        string         `json:"created_at"`
}

type CrmAppUser struct {
	UserID    string        `json:"user_id"`
	StaffID   sql.NullInt64 `json:"staff_id"`
	Email     string        `json:"email"`
	FullName  string        `json:"full_name"`
	Role      string        `json:"role"`
	IsActive  int64         `json:"is_active"`
	CreatedAt string        `json:"created_at"`
	UpdatedAt string        `json:"updated_at"`
}

type CrmConversation struct {
	ConversationID   string         `json:"conversation_id"`
	PartyID          sql.NullString `json:"party_id"`
	Channel          string         `json:"channel"`
	ExternalThreadID string         `json:"external_thread_id"`
	PageID           sql.NullString `json:"page_id"`
	Status           string         `json:"status"`
	AssigneeUserID   sql.NullString `json:"assignee_user_id"`
	LastMessageAt    sql.NullString `json:"last_message_at"`
	UnreadCount      int64          `json:"unread_count"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type CrmCustomFieldDef struct {
	FieldID    string         `json:"field_id"`
	EntityType string         `json:"entity_type"`
	FieldKey   string         `json:"field_key"`
	Label      string         `json:"label"`
	DataType   string         `json:"data_type"`
	Options    sql.NullString `json:"options"`
	IsRequired int64          `json:"is_required"`
	IsActive   int64          `json:"is_active"`
	SortOrder  int64          `json:"sort_order"`
}

type CrmCustomerProfile struct {
	PartyID           string         `json:"party_id"`
	OwnerUserID       sql.NullString `json:"owner_user_id"`
	LifecycleStage    sql.NullString `json:"lifecycle_stage"`
	AcquisitionSource sql.NullString `json:"acquisition_source"`
	Birthday          sql.NullString `json:"birthday"`
	Address           sql.NullString `json:"address"`
	Preferences       sql.NullString `json:"preferences"`
	Custom            string         `json:"custom"`
	ConsentContact    int64          `json:"consent_contact"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

type CrmDedupCandidate struct {
	CandidateID string         `json:"candidate_id"`
	PartyA      string         `json:"party_a"`
	PartyB      string         `json:"party_b"`
	MatchRule   string         `json:"match_rule"`
	MatchScore  float64        `json:"match_score"`
	Status      string         `json:"status"`
	ReviewedBy  sql.NullString `json:"reviewed_by"`
	ReviewedAt  sql.NullString `json:"reviewed_at"`
	CreatedAt   string         `json:"created_at"`
}

type CrmMessage struct {
	MessageID         string         `json:"message_id"`
	ConversationID    string         `json:"conversation_id"`
	ExternalMessageID sql.NullString `json:"external_message_id"`
	Direction         sql.NullString `json:"direction"`
	SenderRef         sql.NullString `json:"sender_ref"`
	Body              sql.NullString `json:"body"`
	Attachments       sql.NullString `json:"attachments"`
	SentAt            string         `json:"sent_at"`
}

type CrmNote struct {
	NoteID       string         `json:"note_id"`
	PartyID      string         `json:"party_id"`
	Body         string         `json:"body"`
	AuthorUserID sql.NullString `json:"author_user_id"`
	CreatedAt    string         `json:"created_at"`
}

type CrmParty struct {
	PartyID      string         `json:"party_id"`
	PartyType    string         `json:"party_type"`
	DisplayName  sql.NullString `json:"display_name"`
	PrimaryPhone sql.NullString `json:"primary_phone"`
	PrimaryEmail sql.NullString `json:"primary_email"`
	Status       string         `json:"status"`
	IsMerged     int64          `json:"is_merged"`
	MergedInto   sql.NullString `json:"merged_into"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type CrmParty360 struct {
	PartyID           string         `json:"party_id"`
	PartyType         string         `json:"party_type"`
	DisplayName       sql.NullString `json:"display_name"`
	PrimaryPhone      sql.NullString `json:"primary_phone"`
	PrimaryEmail      sql.NullString `json:"primary_email"`
	Status            string         `json:"status"`
	IsMerged          int64          `json:"is_merged"`
	PartyCreatedAt    string         `json:"party_created_at"`
	PartyUpdatedAt    string         `json:"party_updated_at"`
	OwnerUserID       sql.NullString `json:"owner_user_id"`
	LifecycleStage    sql.NullString `json:"lifecycle_stage"`
	AcquisitionSource sql.NullString `json:"acquisition_source"`
	Birthday          sql.NullString `json:"birthday"`
	Address           sql.NullString `json:"address"`
	Preferences       sql.NullString `json:"preferences"`
	Custom            sql.NullString `json:"custom"`
	ConsentContact    sql.NullInt64  `json:"consent_contact"`
	ProfileUpdatedAt  sql.NullString `json:"profile_updated_at"`
	TagsJson          interface{}    `json:"tags_json"`
}

type CrmPartyFt struct {
	PartyID  string `json:"party_id"`
	NameNorm string `json:"name_norm"`
}

type CrmPartyIdentity struct {
	IdentityID    string         `json:"identity_id"`
	PartyID       string         `json:"party_id"`
	SourceSystem  string         `json:"source_system"`
	IdentityType  string         `json:"identity_type"`
	IdentityValue string         `json:"identity_value"`
	Confidence    float64        `json:"confidence"`
	IsPrimary     int64          `json:"is_primary"`
	VerifiedAt    sql.NullString `json:"verified_at"`
	CreatedAt     string         `json:"created_at"`
}

type CrmPartyMergeLog struct {
	MergeID          string         `json:"merge_id"`
	SurvivingPartyID string         `json:"surviving_party_id"`
	MergedPartyID    string         `json:"merged_party_id"`
	Reason           sql.NullString `json:"reason"`
	MergedBy         sql.NullString `json:"merged_by"`
	Snapshot         sql.NullString `json:"snapshot"`
	MergedAt         string         `json:"merged_at"`
	UndoneAt         sql.NullString `json:"undone_at"`
}

type CrmPartyTag struct {
	PartyID  string         `json:"party_id"`
	TagID    string         `json:"tag_id"`
	TaggedBy sql.NullString `json:"tagged_by"`
	TaggedAt string         `json:"tagged_at"`
}

type CrmTag struct {
	TagID    string         `json:"tag_id"`
	Name     string         `json:"name"`
	Category sql.NullString `json:"category"`
	Color    sql.NullString `json:"color"`
}

type CrmTask struct {
	TaskID         string         `json:"task_id"`
	PartyID        sql.NullString `json:"party_id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	DueAt          sql.NullString `json:"due_at"`
	Priority       int64          `json:"priority"`
	Status         string         `json:"status"`
	AssigneeUserID sql.NullString `json:"assignee_user_id"`
	Source         string         `json:"source"`
	SourceRef      sql.NullString `json:"source_ref"`
	CreatedBy      sql.NullString `json:"created_by"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
}
