// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type CrmAppUser struct {
	UserID    string        `json:"user_id"`
	StaffID   sql.NullInt64 `json:"staff_id"`
	Email     string        `json:"email"`
	FullName  string        `json:"full_name"`
	Role      string        `json:"role"`
	IsActive  int64         `json:"is_active"`
	CreatedAt string        `json:"created_at"`
	UpdatedAt string        `json:"updated_at"`
}
