// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: note_queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const insertNote = `-- name: InsertNote :exec

INSERT INTO crm_note (note_id, party_id, body, author_user_id, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertNoteParams struct {
	NoteID       string         `json:"note_id"`
	PartyID      string         `json:"party_id"`
	Body         string         `json:"body"`
	AuthorUserID sql.NullString `json:"author_user_id"`
	CreatedAt    string         `json:"created_at"`
}

// Note queries (crm_note)
func (q *Queries) InsertNote(ctx context.Context, arg InsertNoteParams) error {
	_, err := q.db.ExecContext(ctx, insertNote,
		arg.NoteID,
		arg.PartyID,
		arg.Body,
		arg.AuthorUserID,
		arg.CreatedAt,
	)
	return err
}

const listNotesByParty = `-- name: ListNotesByParty :many
SELECT note_id, party_id, body, author_user_id, created_at
FROM crm_note
WHERE party_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListNotesByParty(ctx context.Context, partyID string) ([]CrmNote, error) {
	rows, err := q.db.QueryContext(ctx, listNotesByParty, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmNote
	for rows.Next() {
		var i CrmNote
		if err := rows.Scan(
			&i.NoteID,
			&i.PartyID,
			&i.Body,
			&i.AuthorUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
