// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: party_queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createParty = `-- name: CreateParty :exec

INSERT INTO crm_party (
  party_id, party_type, display_name, primary_phone, primary_email,
  status, is_merged, merged_into, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePartyParams struct {
	PartyID      string         `json:"party_id"`
	PartyType    string         `json:"party_type"`
	DisplayName  sql.NullString `json:"display_name"`
	PrimaryPhone sql.NullString `json:"primary_phone"`
	PrimaryEmail sql.NullString `json:"primary_email"`
	Status       string         `json:"status"`
	IsMerged     int64          `json:"is_merged"`
	MergedInto   sql.NullString `json:"merged_into"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

// Party golden-record queries
func (q *Queries) CreateParty(ctx context.Context, arg CreatePartyParams) error {
	_, err := q.db.ExecContext(ctx, createParty,
		arg.PartyID,
		arg.PartyType,
		arg.DisplayName,
		arg.PrimaryPhone,
		arg.PrimaryEmail,
		arg.Status,
		arg.IsMerged,
		arg.MergedInto,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findPartyByIdentity = `-- name: FindPartyByIdentity :one
SELECT p.party_id, p.party_type, p.display_name, p.primary_phone, p.primary_email,
       p.status, p.is_merged, p.merged_into, p.created_at, p.updated_at
FROM crm_party p
JOIN crm_party_identity i ON i.party_id = p.party_id
WHERE i.identity_type = ?
  AND i.identity_value = ?
LIMIT 1
`

type FindPartyByIdentityParams struct {
	IdentityType  string `json:"identity_type"`
	IdentityValue string `json:"identity_value"`
}

func (q *Queries) FindPartyByIdentity(ctx context.Context, arg FindPartyByIdentityParams) (CrmParty, error) {
	row := q.db.QueryRowContext(ctx, findPartyByIdentity, arg.IdentityType, arg.IdentityValue)
	var i CrmParty
	err := row.Scan(
		&i.PartyID,
		&i.PartyType,
		&i.DisplayName,
		&i.PrimaryPhone,
		&i.PrimaryEmail,
		&i.Status,
		&i.IsMerged,
		&i.MergedInto,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartyByID = `-- name: GetPartyByID :one
SELECT party_id, party_type, display_name, primary_phone, primary_email,
       status, is_merged, merged_into, created_at, updated_at
FROM crm_party
WHERE party_id = ?
LIMIT 1
`

func (q *Queries) GetPartyByID(ctx context.Context, partyID string) (CrmParty, error) {
	row := q.db.QueryRowContext(ctx, getPartyByID, partyID)
	var i CrmParty
	err := row.Scan(
		&i.PartyID,
		&i.PartyType,
		&i.DisplayName,
		&i.PrimaryPhone,
		&i.PrimaryEmail,
		&i.Status,
		&i.IsMerged,
		&i.MergedInto,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdentitiesByParty = `-- name: ListIdentitiesByParty :many
SELECT identity_id, party_id, source_system, identity_type, identity_value,
       confidence, is_primary, verified_at, source_contact_quality, contact_quality, created_at
FROM crm_party_identity
WHERE party_id = ?
ORDER BY is_primary DESC, created_at
`

func (q *Queries) ListIdentitiesByParty(ctx context.Context, partyID string) ([]CrmPartyIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listIdentitiesByParty, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmPartyIdentity
	for rows.Next() {
		var i CrmPartyIdentity
		if err := rows.Scan(
			&i.IdentityID,
			&i.PartyID,
			&i.SourceSystem,
			&i.IdentityType,
			&i.IdentityValue,
			&i.Confidence,
			&i.IsPrimary,
			&i.VerifiedAt,
			&i.SourceContactQuality,
			&i.ContactQuality,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartiesByEmail = `-- name: ListPartiesByEmail :many
SELECT party_id, party_type, display_name, primary_phone, primary_email,
       status, is_merged, merged_into, created_at, updated_at
FROM crm_party
WHERE primary_email = ?
  AND is_merged = 0
`

func (q *Queries) ListPartiesByEmail(ctx context.Context, primaryEmail sql.NullString) ([]CrmParty, error) {
	rows, err := q.db.QueryContext(ctx, listPartiesByEmail, primaryEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmParty
	for rows.Next() {
		var i CrmParty
		if err := rows.Scan(
			&i.PartyID,
			&i.PartyType,
			&i.DisplayName,
			&i.PrimaryPhone,
			&i.PrimaryEmail,
			&i.Status,
			&i.IsMerged,
			&i.MergedInto,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartiesByPhone = `-- name: ListPartiesByPhone :many
SELECT party_id, party_type, display_name, primary_phone, primary_email,
       status, is_merged, merged_into, created_at, updated_at
FROM crm_party
WHERE primary_phone = ?
  AND is_merged = 0
`

func (q *Queries) ListPartiesByPhone(ctx context.Context, primaryPhone sql.NullString) ([]CrmParty, error) {
	rows, err := q.db.QueryContext(ctx, listPartiesByPhone, primaryPhone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmParty
	for rows.Next() {
		var i CrmParty
		if err := rows.Scan(
			&i.PartyID,
			&i.PartyType,
			&i.DisplayName,
			&i.PrimaryPhone,
			&i.PrimaryEmail,
			&i.Status,
			&i.IsMerged,
			&i.MergedInto,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignIdentity = `-- name: ReassignIdentity :exec
UPDATE crm_party_identity
SET party_id = ?
WHERE identity_id = ?
`

type ReassignIdentityParams struct {
	PartyID    string `json:"party_id"`
	IdentityID string `json:"identity_id"`
}

func (q *Queries) ReassignIdentity(ctx context.Context, arg ReassignIdentityParams) error {
	_, err := q.db.ExecContext(ctx, reassignIdentity, arg.PartyID, arg.IdentityID)
	return err
}

const updateParty = `-- name: UpdateParty :exec
UPDATE crm_party
SET display_name  = ?,
    primary_phone = ?,
    primary_email = ?,
    status        = ?,
    is_merged     = ?,
    merged_into   = ?
WHERE party_id = ?
`

type UpdatePartyParams struct {
	DisplayName  sql.NullString `json:"display_name"`
	PrimaryPhone sql.NullString `json:"primary_phone"`
	PrimaryEmail sql.NullString `json:"primary_email"`
	Status       string         `json:"status"`
	IsMerged     int64          `json:"is_merged"`
	MergedInto   sql.NullString `json:"merged_into"`
	PartyID      string         `json:"party_id"`
}

func (q *Queries) UpdateParty(ctx context.Context, arg UpdatePartyParams) error {
	_, err := q.db.ExecContext(ctx, updateParty,
		arg.DisplayName,
		arg.PrimaryPhone,
		arg.PrimaryEmail,
		arg.Status,
		arg.IsMerged,
		arg.MergedInto,
		arg.PartyID,
	)
	return err
}

const upsertPartyIdentity = `-- name: UpsertPartyIdentity :exec

INSERT OR IGNORE INTO crm_party_identity (
  identity_id, party_id, source_system, identity_type, identity_value,
  confidence, is_primary, verified_at, source_contact_quality, contact_quality, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type UpsertPartyIdentityParams struct {
	IdentityID           string         `json:"identity_id"`
	PartyID              string         `json:"party_id"`
	SourceSystem         string         `json:"source_system"`
	IdentityType         string         `json:"identity_type"`
	IdentityValue        string         `json:"identity_value"`
	Confidence           float64        `json:"confidence"`
	IsPrimary            int64          `json:"is_primary"`
	VerifiedAt           sql.NullString `json:"verified_at"`
	SourceContactQuality string         `json:"source_contact_quality"`
	ContactQuality       string         `json:"contact_quality"`
	CreatedAt            string         `json:"created_at"`
}

// Party identity queries
func (q *Queries) UpsertPartyIdentity(ctx context.Context, arg UpsertPartyIdentityParams) error {
	_, err := q.db.ExecContext(ctx, upsertPartyIdentity,
		arg.IdentityID,
		arg.PartyID,
		arg.SourceSystem,
		arg.IdentityType,
		arg.IdentityValue,
		arg.Confidence,
		arg.IsPrimary,
		arg.VerifiedAt,
		arg.SourceContactQuality,
		arg.ContactQuality,
		arg.CreatedAt,
	)
	return err
}

const updateIdentityContactQuality = `-- name: UpdateIdentityContactQuality :exec
UPDATE crm_party_identity
SET contact_quality = ?
WHERE identity_id = ?
`

type UpdateIdentityContactQualityParams struct {
	ContactQuality string `json:"contact_quality"`
	IdentityID     string `json:"identity_id"`
}

func (q *Queries) UpdateIdentityContactQuality(ctx context.Context, arg UpdateIdentityContactQualityParams) error {
	_, err := q.db.ExecContext(ctx, updateIdentityContactQuality, arg.ContactQuality, arg.IdentityID)
	return err
}
