// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile_queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getCustomerProfile = `-- name: GetCustomerProfile :one

SELECT party_id, owner_user_id, lifecycle_stage, acquisition_source,
       birthday, address, preferences, custom, consent_contact,
       created_at, updated_at
FROM crm_customer_profile
WHERE party_id = ?
LIMIT 1
`

// Customer profile queries (crm_customer_profile)
func (q *Queries) GetCustomerProfile(ctx context.Context, partyID string) (CrmCustomerProfile, error) {
	row := q.db.QueryRowContext(ctx, getCustomerProfile, partyID)
	var i CrmCustomerProfile
	err := row.Scan(
		&i.PartyID,
		&i.OwnerUserID,
		&i.LifecycleStage,
		&i.AcquisitionSource,
		&i.Birthday,
		&i.Address,
		&i.Preferences,
		&i.Custom,
		&i.ConsentContact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParty360 = `-- name: GetParty360 :one
SELECT
  party_id, party_type, display_name, primary_phone, primary_email,
  status, is_merged, party_created_at, party_updated_at,
  owner_user_id, lifecycle_stage, acquisition_source, birthday,
  address, preferences, custom, consent_contact, profile_updated_at,
  tags_json
FROM crm_party_360
WHERE party_id = ?
LIMIT 1
`

func (q *Queries) GetParty360(ctx context.Context, partyID string) (CrmParty360, error) {
	row := q.db.QueryRowContext(ctx, getParty360, partyID)
	var i CrmParty360
	err := row.Scan(
		&i.PartyID,
		&i.PartyType,
		&i.DisplayName,
		&i.PrimaryPhone,
		&i.PrimaryEmail,
		&i.Status,
		&i.IsMerged,
		&i.PartyCreatedAt,
		&i.PartyUpdatedAt,
		&i.OwnerUserID,
		&i.LifecycleStage,
		&i.AcquisitionSource,
		&i.Birthday,
		&i.Address,
		&i.Preferences,
		&i.Custom,
		&i.ConsentContact,
		&i.ProfileUpdatedAt,
		&i.TagsJson,
	)
	return i, err
}

const updateCustomJSON = `-- name: UpdateCustomJSON :exec
UPDATE crm_customer_profile
SET custom     = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE party_id = ?
`

type UpdateCustomJSONParams struct {
	Custom  string `json:"custom"`
	PartyID string `json:"party_id"`
}

func (q *Queries) UpdateCustomJSON(ctx context.Context, arg UpdateCustomJSONParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomJSON, arg.Custom, arg.PartyID)
	return err
}

const upsertCustomerProfile = `-- name: UpsertCustomerProfile :exec
INSERT INTO crm_customer_profile (
  party_id, owner_user_id, lifecycle_stage, acquisition_source,
  birthday, address, preferences, custom, consent_contact,
  created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (party_id) DO UPDATE SET
  owner_user_id      = excluded.owner_user_id,
  lifecycle_stage    = excluded.lifecycle_stage,
  acquisition_source = excluded.acquisition_source,
  birthday           = excluded.birthday,
  address            = excluded.address,
  preferences        = excluded.preferences,
  custom             = excluded.custom,
  consent_contact    = excluded.consent_contact,
  updated_at         = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

type UpsertCustomerProfileParams struct {
	PartyID           string         `json:"party_id"`
	OwnerUserID       sql.NullString `json:"owner_user_id"`
	LifecycleStage    sql.NullString `json:"lifecycle_stage"`
	AcquisitionSource sql.NullString `json:"acquisition_source"`
	Birthday          sql.NullString `json:"birthday"`
	Address           sql.NullString `json:"address"`
	Preferences       sql.NullString `json:"preferences"`
	Custom            string         `json:"custom"`
	ConsentContact    int64          `json:"consent_contact"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

func (q *Queries) UpsertCustomerProfile(ctx context.Context, arg UpsertCustomerProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertCustomerProfile,
		arg.PartyID,
		arg.OwnerUserID,
		arg.LifecycleStage,
		arg.AcquisitionSource,
		arg.Birthday,
		arg.Address,
		arg.Preferences,
		arg.Custom,
		arg.ConsentContact,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
