// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segment_queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteRuleSegmentMembers = `-- name: DeleteRuleSegmentMembers :exec
DELETE FROM crm_segment_member
WHERE segment_id = ? AND source = 'rule'
`

func (q *Queries) DeleteRuleSegmentMembers(ctx context.Context, segmentID string) error {
	_, err := q.db.ExecContext(ctx, deleteRuleSegmentMembers, segmentID)
	return err
}

const deleteSegmentMember = `-- name: DeleteSegmentMember :exec
DELETE FROM crm_segment_member
WHERE segment_id = ? AND party_id = ?
`

type DeleteSegmentMemberParams struct {
	SegmentID string `json:"segment_id"`
	PartyID   string `json:"party_id"`
}

func (q *Queries) DeleteSegmentMember(ctx context.Context, arg DeleteSegmentMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteSegmentMember, arg.SegmentID, arg.PartyID)
	return err
}

const getSegmentByID = `-- name: GetSegmentByID :one
SELECT
  segment_id, name, description, is_dynamic, definition, owner_user_id, created_at, updated_at
FROM crm_segment
WHERE segment_id = ?
`

func (q *Queries) GetSegmentByID(ctx context.Context, segmentID string) (CrmSegment, error) {
	row := q.db.QueryRowContext(ctx, getSegmentByID, segmentID)
	var i CrmSegment
	err := row.Scan(
		&i.SegmentID,
		&i.Name,
		&i.Description,
		&i.IsDynamic,
		&i.Definition,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSegment = `-- name: InsertSegment :exec

INSERT INTO crm_segment (
  segment_id, name, description, is_dynamic, definition, owner_user_id, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSegmentParams struct {
	SegmentID   string         `json:"segment_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsDynamic   int64          `json:"is_dynamic"`
	Definition  sql.NullString `json:"definition"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

// Segment queries (crm_segment, crm_segment_member)
func (q *Queries) InsertSegment(ctx context.Context, arg InsertSegmentParams) error {
	_, err := q.db.ExecContext(ctx, insertSegment,
		arg.SegmentID,
		arg.Name,
		arg.Description,
		arg.IsDynamic,
		arg.Definition,
		arg.OwnerUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listSegmentMembers = `-- name: ListSegmentMembers :many
SELECT segment_id, party_id, source, added_at
FROM crm_segment_member
WHERE segment_id = ?
ORDER BY added_at DESC
`

func (q *Queries) ListSegmentMembers(ctx context.Context, segmentID string) ([]CrmSegmentMember, error) {
	rows, err := q.db.QueryContext(ctx, listSegmentMembers, segmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmSegmentMember
	for rows.Next() {
		var i CrmSegmentMember
		if err := rows.Scan(
			&i.SegmentID,
			&i.PartyID,
			&i.Source,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegments = `-- name: ListSegments :many
SELECT
  segment_id, name, description, is_dynamic, definition, owner_user_id, created_at, updated_at
FROM crm_segment
ORDER BY created_at DESC
`

func (q *Queries) ListSegments(ctx context.Context) ([]CrmSegment, error) {
	rows, err := q.db.QueryContext(ctx, listSegments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmSegment
	for rows.Next() {
		var i CrmSegment
		if err := rows.Scan(
			&i.SegmentID,
			&i.Name,
			&i.Description,
			&i.IsDynamic,
			&i.Definition,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSegment = `-- name: UpdateSegment :exec
UPDATE crm_segment
SET
  name          = ?,
  description   = ?,
  is_dynamic    = ?,
  definition    = ?,
  owner_user_id = ?,
  updated_at    = ?
WHERE segment_id = ?
`

type UpdateSegmentParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsDynamic   int64          `json:"is_dynamic"`
	Definition  sql.NullString `json:"definition"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	UpdatedAt   string         `json:"updated_at"`
	SegmentID   string         `json:"segment_id"`
}

func (q *Queries) UpdateSegment(ctx context.Context, arg UpdateSegmentParams) error {
	_, err := q.db.ExecContext(ctx, updateSegment,
		arg.Name,
		arg.Description,
		arg.IsDynamic,
		arg.Definition,
		arg.OwnerUserID,
		arg.UpdatedAt,
		arg.SegmentID,
	)
	return err
}

const upsertSegmentMember = `-- name: UpsertSegmentMember :exec
INSERT INTO crm_segment_member (segment_id, party_id, source, added_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (segment_id, party_id) DO UPDATE SET
  source   = CASE WHEN crm_segment_member.source = 'manual' THEN 'manual' ELSE excluded.source END,
  added_at = excluded.added_at
`

type UpsertSegmentMemberParams struct {
	SegmentID string `json:"segment_id"`
	PartyID   string `json:"party_id"`
	Source    string `json:"source"`
	AddedAt   string `json:"added_at"`
}

func (q *Queries) UpsertSegmentMember(ctx context.Context, arg UpsertSegmentMemberParams) error {
	_, err := q.db.ExecContext(ctx, upsertSegmentMember,
		arg.SegmentID,
		arg.PartyID,
		arg.Source,
		arg.AddedAt,
	)
	return err
}
