// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag_queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const attachPartyTag = `-- name: AttachPartyTag :exec
INSERT OR IGNORE INTO crm_party_tag (party_id, tag_id, tagged_by, tagged_at)
VALUES (?, ?, ?, ?)
`

type AttachPartyTagParams struct {
	PartyID  string         `json:"party_id"`
	TagID    string         `json:"tag_id"`
	TaggedBy sql.NullString `json:"tagged_by"`
	TaggedAt string         `json:"tagged_at"`
}

func (q *Queries) AttachPartyTag(ctx context.Context, arg AttachPartyTagParams) error {
	_, err := q.db.ExecContext(ctx, attachPartyTag,
		arg.PartyID,
		arg.TagID,
		arg.TaggedBy,
		arg.TaggedAt,
	)
	return err
}

const createTag = `-- name: CreateTag :exec
INSERT INTO crm_tag (tag_id, name, category, color)
VALUES (?, ?, ?, ?)
`

type CreateTagParams struct {
	TagID    string         `json:"tag_id"`
	Name     string         `json:"name"`
	Category sql.NullString `json:"category"`
	Color    sql.NullString `json:"color"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) error {
	_, err := q.db.ExecContext(ctx, createTag,
		arg.TagID,
		arg.Name,
		arg.Category,
		arg.Color,
	)
	return err
}

const detachPartyTag = `-- name: DetachPartyTag :exec
DELETE FROM crm_party_tag
WHERE party_id = ? AND tag_id = ?
`

type DetachPartyTagParams struct {
	PartyID string `json:"party_id"`
	TagID   string `json:"tag_id"`
}

func (q *Queries) DetachPartyTag(ctx context.Context, arg DetachPartyTagParams) error {
	_, err := q.db.ExecContext(ctx, detachPartyTag, arg.PartyID, arg.TagID)
	return err
}

const getCustomFieldDef = `-- name: GetCustomFieldDef :one
SELECT field_id, entity_type, field_key, label, data_type,
       options, is_required, is_active, sort_order
FROM crm_custom_field_def
WHERE field_id = ?
LIMIT 1
`

func (q *Queries) GetCustomFieldDef(ctx context.Context, fieldID string) (CrmCustomFieldDef, error) {
	row := q.db.QueryRowContext(ctx, getCustomFieldDef, fieldID)
	var i CrmCustomFieldDef
	err := row.Scan(
		&i.FieldID,
		&i.EntityType,
		&i.FieldKey,
		&i.Label,
		&i.DataType,
		&i.Options,
		&i.IsRequired,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT tag_id, name, category, color
FROM crm_tag
WHERE tag_id = ?
LIMIT 1
`

func (q *Queries) GetTag(ctx context.Context, tagID string) (CrmTag, error) {
	row := q.db.QueryRowContext(ctx, getTag, tagID)
	var i CrmTag
	err := row.Scan(
		&i.TagID,
		&i.Name,
		&i.Category,
		&i.Color,
	)
	return i, err
}

const insertCustomFieldDef = `-- name: InsertCustomFieldDef :exec
INSERT INTO crm_custom_field_def (
  field_id, entity_type, field_key, label, data_type,
  options, is_required, is_active, sort_order
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCustomFieldDefParams struct {
	FieldID    string         `json:"field_id"`
	EntityType string         `json:"entity_type"`
	FieldKey   string         `json:"field_key"`
	Label      string         `json:"label"`
	DataType   string         `json:"data_type"`
	Options    sql.NullString `json:"options"`
	IsRequired int64          `json:"is_required"`
	IsActive   int64          `json:"is_active"`
	SortOrder  int64          `json:"sort_order"`
}

func (q *Queries) InsertCustomFieldDef(ctx context.Context, arg InsertCustomFieldDefParams) error {
	_, err := q.db.ExecContext(ctx, insertCustomFieldDef,
		arg.FieldID,
		arg.EntityType,
		arg.FieldKey,
		arg.Label,
		arg.DataType,
		arg.Options,
		arg.IsRequired,
		arg.IsActive,
		arg.SortOrder,
	)
	return err
}

const listActiveCustomFieldDefs = `-- name: ListActiveCustomFieldDefs :many

SELECT field_id, entity_type, field_key, label, data_type,
       options, is_required, is_active, sort_order
FROM crm_custom_field_def
WHERE entity_type = ? AND is_active = 1
ORDER BY sort_order, field_key
`

// Custom field definition queries
func (q *Queries) ListActiveCustomFieldDefs(ctx context.Context, entityType string) ([]CrmCustomFieldDef, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCustomFieldDefs, entityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmCustomFieldDef
	for rows.Next() {
		var i CrmCustomFieldDef
		if err := rows.Scan(
			&i.FieldID,
			&i.EntityType,
			&i.FieldKey,
			&i.Label,
			&i.DataType,
			&i.Options,
			&i.IsRequired,
			&i.IsActive,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCustomFieldDefs = `-- name: ListAllCustomFieldDefs :many
SELECT field_id, entity_type, field_key, label, data_type,
       options, is_required, is_active, sort_order
FROM crm_custom_field_def
WHERE entity_type = ?
ORDER BY sort_order, field_key
`

func (q *Queries) ListAllCustomFieldDefs(ctx context.Context, entityType string) ([]CrmCustomFieldDef, error) {
	rows, err := q.db.QueryContext(ctx, listAllCustomFieldDefs, entityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmCustomFieldDef
	for rows.Next() {
		var i CrmCustomFieldDef
		if err := rows.Scan(
			&i.FieldID,
			&i.EntityType,
			&i.FieldKey,
			&i.Label,
			&i.DataType,
			&i.Options,
			&i.IsRequired,
			&i.IsActive,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTags = `-- name: ListAllTags :many
SELECT tag_id, name, category, color
FROM crm_tag
ORDER BY category, name
`

func (q *Queries) ListAllTags(ctx context.Context) ([]CrmTag, error) {
	rows, err := q.db.QueryContext(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmTag
	for rows.Next() {
		var i CrmTag
		if err := rows.Scan(
			&i.TagID,
			&i.Name,
			&i.Category,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartyTags = `-- name: ListPartyTags :many
SELECT t.tag_id, t.name, t.category, t.color
FROM crm_tag t
JOIN crm_party_tag pt ON pt.tag_id = t.tag_id
WHERE pt.party_id = ?
ORDER BY t.category, t.name
`

func (q *Queries) ListPartyTags(ctx context.Context, partyID string) ([]CrmTag, error) {
	rows, err := q.db.QueryContext(ctx, listPartyTags, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmTag
	for rows.Next() {
		var i CrmTag
		if err := rows.Scan(
			&i.TagID,
			&i.Name,
			&i.Category,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByCategory = `-- name: ListTagsByCategory :many

SELECT tag_id, name, category, color
FROM crm_tag
WHERE category = ?
ORDER BY name
`

// Tag and party-tag queries
func (q *Queries) ListTagsByCategory(ctx context.Context, category sql.NullString) ([]CrmTag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmTag
	for rows.Next() {
		var i CrmTag
		if err := rows.Scan(
			&i.TagID,
			&i.Name,
			&i.Category,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomFieldDef = `-- name: UpdateCustomFieldDef :exec
UPDATE crm_custom_field_def
SET label       = ?,
    options     = ?,
    is_required = ?,
    is_active   = ?,
    sort_order  = ?
WHERE field_id = ?
`

type UpdateCustomFieldDefParams struct {
	Label      string         `json:"label"`
	Options    sql.NullString `json:"options"`
	IsRequired int64          `json:"is_required"`
	IsActive   int64          `json:"is_active"`
	SortOrder  int64          `json:"sort_order"`
	FieldID    string         `json:"field_id"`
}

func (q *Queries) UpdateCustomFieldDef(ctx context.Context, arg UpdateCustomFieldDefParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomFieldDef,
		arg.Label,
		arg.Options,
		arg.IsRequired,
		arg.IsActive,
		arg.SortOrder,
		arg.FieldID,
	)
	return err
}
