// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_queries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const existsTaskBySourceRef = `-- name: ExistsTaskBySourceRef :one
SELECT COUNT(*) FROM crm_task
WHERE source = ? AND source_ref = ?
`

type ExistsTaskBySourceRefParams struct {
	Source    string         `json:"source"`
	SourceRef sql.NullString `json:"source_ref"`
}

func (q *Queries) ExistsTaskBySourceRef(ctx context.Context, arg ExistsTaskBySourceRefParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsTaskBySourceRef, arg.Source, arg.SourceRef)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT
  task_id, party_id, title, description, due_at, priority, status,
  assignee_user_id, source, source_ref, created_by, created_at, updated_at, completed_at
FROM crm_task
WHERE task_id = ?
`

func (q *Queries) GetTaskByID(ctx context.Context, taskID string) (CrmTask, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, taskID)
	var i CrmTask
	err := row.Scan(
		&i.TaskID,
		&i.PartyID,
		&i.Title,
		&i.Description,
		&i.DueAt,
		&i.Priority,
		&i.Status,
		&i.AssigneeUserID,
		&i.Source,
		&i.SourceRef,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :exec

INSERT INTO crm_task (
  task_id, party_id, title, description, due_at, priority, status,
  assignee_user_id, source, source_ref, created_by, created_at, updated_at, completed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTaskParams struct {
	TaskID         string         `json:"task_id"`
	PartyID        sql.NullString `json:"party_id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	DueAt          sql.NullString `json:"due_at"`
	Priority       int64          `json:"priority"`
	Status         string         `json:"status"`
	AssigneeUserID sql.NullString `json:"assignee_user_id"`
	Source         string         `json:"source"`
	SourceRef      sql.NullString `json:"source_ref"`
	CreatedBy      sql.NullString `json:"created_by"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
}

// Task queries (crm_task)
func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertTask,
		arg.TaskID,
		arg.PartyID,
		arg.Title,
		arg.Description,
		arg.DueAt,
		arg.Priority,
		arg.Status,
		arg.AssigneeUserID,
		arg.Source,
		arg.SourceRef,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
	)
	return err
}

const listAllTasks = `-- name: ListAllTasks :many
SELECT
  task_id, party_id, title, description, due_at, priority, status,
  assignee_user_id, source, source_ref, created_by, created_at, updated_at, completed_at
FROM crm_task
ORDER BY due_at ASC, priority DESC
`

func (q *Queries) ListAllTasks(ctx context.Context) ([]CrmTask, error) {
	rows, err := q.db.QueryContext(ctx, listAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmTask
	for rows.Next() {
		var i CrmTask
		if err := rows.Scan(
			&i.TaskID,
			&i.PartyID,
			&i.Title,
			&i.Description,
			&i.DueAt,
			&i.Priority,
			&i.Status,
			&i.AssigneeUserID,
			&i.Source,
			&i.SourceRef,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByAssignee = `-- name: ListTasksByAssignee :many
SELECT
  task_id, party_id, title, description, due_at, priority, status,
  assignee_user_id, source, source_ref, created_by, created_at, updated_at, completed_at
FROM crm_task
WHERE assignee_user_id = ?
ORDER BY due_at ASC, priority DESC
`

func (q *Queries) ListTasksByAssignee(ctx context.Context, assigneeUserID sql.NullString) ([]CrmTask, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByAssignee, assigneeUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmTask
	for rows.Next() {
		var i CrmTask
		if err := rows.Scan(
			&i.TaskID,
			&i.PartyID,
			&i.Title,
			&i.Description,
			&i.DueAt,
			&i.Priority,
			&i.Status,
			&i.AssigneeUserID,
			&i.Source,
			&i.SourceRef,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByAssigneeAndStatus = `-- name: ListTasksByAssigneeAndStatus :many
SELECT
  task_id, party_id, title, description, due_at, priority, status,
  assignee_user_id, source, source_ref, created_by, created_at, updated_at, completed_at
FROM crm_task
WHERE assignee_user_id = ? AND status = ?
ORDER BY due_at ASC, priority DESC
`

type ListTasksByAssigneeAndStatusParams struct {
	AssigneeUserID sql.NullString `json:"assignee_user_id"`
	Status         string         `json:"status"`
}

func (q *Queries) ListTasksByAssigneeAndStatus(ctx context.Context, arg ListTasksByAssigneeAndStatusParams) ([]CrmTask, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByAssigneeAndStatus, arg.AssigneeUserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmTask
	for rows.Next() {
		var i CrmTask
		if err := rows.Scan(
			&i.TaskID,
			&i.PartyID,
			&i.Title,
			&i.Description,
			&i.DueAt,
			&i.Priority,
			&i.Status,
			&i.AssigneeUserID,
			&i.Source,
			&i.SourceRef,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT
  task_id, party_id, title, description, due_at, priority, status,
  assignee_user_id, source, source_ref, created_by, created_at, updated_at, completed_at
FROM crm_task
WHERE status = ?
ORDER BY due_at ASC, priority DESC
`

func (q *Queries) ListTasksByStatus(ctx context.Context, status string) ([]CrmTask, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmTask
	for rows.Next() {
		var i CrmTask
		if err := rows.Scan(
			&i.TaskID,
			&i.PartyID,
			&i.Title,
			&i.Description,
			&i.DueAt,
			&i.Priority,
			&i.Status,
			&i.AssigneeUserID,
			&i.Source,
			&i.SourceRef,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE crm_task
SET
  title            = ?,
  description      = ?,
  status           = ?,
  assignee_user_id = ?,
  due_at           = ?,
  completed_at     = ?,
  updated_at       = ?
WHERE task_id = ?
`

type UpdateTaskParams struct {
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	Status         string         `json:"status"`
	AssigneeUserID sql.NullString `json:"assignee_user_id"`
	DueAt          sql.NullString `json:"due_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
	UpdatedAt      string         `json:"updated_at"`
	TaskID         string         `json:"task_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.AssigneeUserID,
		arg.DueAt,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.TaskID,
	)
	return err
}
