// build.mjs — generate machine-readable artifacts into generated/.
// DO NOT edit generated/ by hand. Run after validate.
// Output: surface-registry.yaml, navigation-graph.yaml, action-registry.csv, coverage-report.md
//         wireframe-v2.html (generated via generateWireframe — browser NOT opened)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, basename } from "node:path";
import yaml from "js-yaml";
import { extractAll, listSpecFiles, SPEC_ROOT } from "./extract.mjs";
import { generateWireframe } from "./interpret-wireframe.mjs";
import { generateAscii, injectAscii } from "./wireframe/generate-ascii.mjs";
import { extractLayout } from "./wireframe/extract-layout.mjs";
import { auditChips, renderChipAuditMd } from "./wireframe/chip-audit.mjs";

const OUT = join(SPEC_ROOT, "generated");
mkdirSync(OUT, { recursive: true });

const allFiles = extractAll();
// Fail hard on broken files: a broken surface would be silently dropped, corrupting the build.
const brokenFiles = allFiles.filter((f) => f.errors.length > 0);
if (brokenFiles.length) {
  for (const f of brokenFiles) {
    for (const e of f.errors) console.error(`✗ [${f.file}] ${e}`);
  }
  console.error(`\nBuild aborted: ${brokenFiles.length} file(s) had extraction errors. Run validate first.`);
  process.exit(1);
}
const files = allFiles.filter((f) => f.contract);
const HEADER = "# GENERATED by ui-spec-tools/build.mjs — DO NOT EDIT BY HAND. Source = surface *.md\n";

// ---- surface-registry.yaml ----
const registry = { surfaces: {} };
for (const f of files) {
  const m = f.meta || {};
  if (!m.id) continue;
  registry.surfaces[m.id] = {
    type:      m.type,
    name:      m.name,
    platforms: m.platforms || [],
    hosts:     m.hosts     || [],
    status:    m.status    || "active",
    file:      f.file,
    rules:     m.rules     || [],
    regions:   m.regions   || [],
  };
}
writeFileSync(join(OUT, "surface-registry.yaml"), HEADER + yaml.dump(registry, { lineWidth: 120 }));

// ---- navigation-graph.yaml + action-registry.csv ----
const edges = [];
for (const f of files) {
  const m = f.meta || {};
  const c = f.contract;

  const pushEdge = (it, kind) => {
    // Strip internal _autoId marker from output
    const { _autoId, ...clean } = it;
    edges.push({
      id:          clean.id,
      from:        m.id,
      element:     clean.element,
      trigger:     clean.trigger,
      listens_to:  clean.listens_to,
      guard:       clean.guard,
      action:      clean.action ?? (kind === "emit" ? "emit_event" : undefined),
      target:      clean.target,
      event:       clean.event,
      payload:     clean.payload,
      effects:     clean.effects,
      region:      clean.region,
    });
  };

  for (const it of c.interactions || []) pushEdge(it, "interaction");
  for (const em of c.emits        || []) pushEdge(em, "emit");
}

// Strip undefined keys for clean YAML output
const cleanEdges = edges.map((e) =>
  Object.fromEntries(Object.entries(e).filter(([, v]) => v !== undefined))
);

writeFileSync(
  join(OUT, "navigation-graph.yaml"),
  HEADER + yaml.dump({ surfaces: Object.keys(registry.surfaces), edges: cleanEdges }, { lineWidth: 120 })
);

// action-registry.csv — flat table for spreadsheet/tooling consumption
const csvRows = [["id", "from", "element", "trigger", "action", "target", "guard", "region"]];
for (const e of cleanEdges) {
  csvRows.push([
    e.id        ?? "",
    e.from      ?? "",
    e.element   ?? "",
    e.trigger   ?? e.listens_to ?? "",
    e.action    ?? "",
    e.target    ?? "",
    (e.guard    ?? "").replaceAll(",", ";"),
    e.region    ?? "",
  ]);
}
writeFileSync(join(OUT, "action-registry.csv"), csvRows.map((r) => r.join(",")).join("\n") + "\n");

// ---- coverage-report.md ----
const flows = files.filter((f) => f.meta?.type === "flow" && f.contract?.flow);
const actionIds = new Set(cleanEdges.map((e) => e.id));

let cov = `<!-- GENERATED by ui-spec-tools/build.mjs — DO NOT EDIT BY HAND. Source = surface *.md -->\n\n`;
cov += `# Coverage Report (generated)\n\n`;
cov += `Surfaces: ${Object.keys(registry.surfaces).length} · Actions: ${cleanEdges.length} · Flows: ${flows.length}\n\n`;
cov += `## Flow → Actions\n\n| Flow | Goal | Steps | Missing action refs |\n|---|---|---|---|\n`;

for (const f of flows) {
  const fl = f.contract.flow;
  const steps   = (fl.steps    || []).concat((fl.branches || []).map((b) => b.action));
  const missing = steps.filter((s) => !actionIds.has(s));
  cov += `| ${f.meta.id} | ${fl.goal ?? ""} | ${(fl.steps || []).join(" → ")} | ${missing.length ? missing.join(", ") : "—"} |\n`;
}

writeFileSync(join(OUT, "coverage-report.md"), cov);

console.log(`✓ built generated/: surface-registry.yaml, navigation-graph.yaml, action-registry.csv, coverage-report.md`);
console.log(`  surfaces=${Object.keys(registry.surfaces).length} actions=${cleanEdges.length} flows=${flows.length}`);

// ---- ASCII injection (phase 7) + chip-audit collection ----
// MUST run BEFORE wireframe generation: the wireframe embeds spec prose (Blueprint
// tab reads the generated ASCII from the .md), and writing .md files after the
// wireframe would leave spec mtimes newer than the wireframe — a false-positive
// VR-WIREFRAME-STALE on the very next validate.
// For every surface with a yaml ui-layout model: regenerate ASCII and inject
// between <!-- ui-layout:ascii:start/end --> markers. Idempotent: only writes
// the file when the generated content differs from the current content.
// Surfaces are also collected here for the chip-audit (phase 7.5) below.
{
  // Build file-path → surface-ID map so chip-audit can label each surface.
  const fileIdMap = new Map(
    allFiles
      .filter((f) => f.meta?.id && f.file)
      .map((f) => [join(SPEC_ROOT, f.file), f.meta.id])
  );

  const specFiles = listSpecFiles();
  let asciiChanged = 0, asciiSkipped = 0;
  const auditSurfaces = [];

  for (const absPath of specFiles) {
    let raw;
    try { raw = readFileSync(absPath, "utf8"); } catch { asciiSkipped++; continue; }
    const layout = extractLayout(raw);
    if (!layout) { asciiSkipped++; continue; }

    // Collect for chip-audit: prefer ID from extract map, fall back to filename stem.
    const surfaceId = fileIdMap.get(absPath) ?? basename(absPath, ".md");
    auditSurfaces.push({ surfaceId, layout });

    const ascii   = generateAscii(layout);
    const updated = injectAscii(raw, ascii);
    if (updated !== raw) {
      writeFileSync(absPath, updated, "utf8");
      asciiChanged++;
      console.log(`  ascii regenerated: ${absPath.replace(SPEC_ROOT + "/", "").replace(SPEC_ROOT + "\\", "")}`);
    }
  }
  const total = specFiles.length - asciiSkipped;
  if (asciiChanged === 0) {
    console.log(`✓ ascii: ${total} surface(s) with layout — all up to date`);
  } else {
    console.log(`✓ ascii: regenerated ${asciiChanged}/${total} surface(s) with layout`);
  }

  // ---- chip-audit (phase 7.5) ----
  // Run after ASCII injection (spec .md files are now up to date) and before
  // wireframe generation. Idempotent: only writes chip-audit.md when content differs.
  {
    const auditResult = auditChips(auditSurfaces);
    const { totals } = auditResult;
    const auditMd = renderChipAuditMd(auditResult);
    const auditPath = join(OUT, "chip-audit.md");
    let existing = "";
    try { existing = readFileSync(auditPath, "utf8"); } catch { /* first run */ }
    if (auditMd !== existing) writeFileSync(auditPath, auditMd, "utf8");
    console.log(
      `✓ chip-audit: ${totals.tokens} tokens · ${totals.mapped} mapped · ${totals.unmapped} unmapped → generated/chip-audit.md`
    );
  }
}

// ---- wireframe-v2.html ----
// Regenerate wireframe so one build command refreshes all outputs together.
// Runs last: reads the .md files (incl. freshly injected ASCII) — see note above.
// open:false — never auto-open browser in a build pipeline step.
generateWireframe(SPEC_ROOT, { open: false });
console.log(`✓ built generated/wireframe-v2.html`);
