name: 'sapo_warehouse'
version: '1.0.0'
config-version: 2

profile: 'sapo_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


# Dispatch configuration
dispatch:
  - macro_namespace: dbt
    search_order: ['sapo_warehouse', 'dbt']

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  sapo_warehouse:
    # Config for all models
    +materialized: view  # Default to view for lightweight transformations
    
    staging:
      +schema: staging
      +materialized: view
      +tags: ["otp"]
    
    # intermediate:
    #   +schema: intermediate
    #   +materialized: table
    #   +tags: ["otp"]

    marts:
      +schema: marts
      +materialized: external
      +options:
        format: 'parquet'
      +tags: ["olap"]
      +on_schema_change: sync_all_columns

vars:
  external_root: "{{ env_var('DBT_EXPORT_PATH') }}"
