sapo_warehouse:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../data_lake/sapo_warehouse.duckdb'  # Persistent DuckDB file in data_lake
      threads: 1
      extensions:
        - parquet
        - httpfs # if reading from S3/remote in future
      external_root: "{{ env_var('DBT_EXPORT_PATH') }}"
      settings:
        memory_limit: '24GB'
        preserve_insertion_order: false
        temp_directory: 'dbt_tmp'
