// chip-audit.mjs — detect [token] chips in samples: that have no elements: mapping.
// A chip is "unmapped" when its bracket-text has no key in the layout's elements:{} map.
//
// Exported API (pure — no config.mjs dependency; safe to import in tests):
//   auditChips(surfaces)      → { entries: [{surfaceId, region, token, status}], totals }
//   renderChipAuditMd(result) → markdown string (deterministic, no timestamps)
//
// CLI: node tools/wireframe/chip-audit.mjs --root <spec-root>
//   Prints summary line + writes <spec-root>/generated/chip-audit.md (idempotent).
//   config.mjs / extract.mjs / gray-matter are loaded via dynamic import only in the
//   CLI path so that importing this module in test contexts does not call loadConfig().

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, basename } from "node:path";
import { CONTENT_TYPES, walkContent, contentElementLabel, contentElementHasAction } from "./layout-schema.mjs";

/** Match [token] where token contains no nested brackets and is at least 1 char. */
const CHIP_RE = /\[([^\[\]]+)\]/g;

/**
 * Extract all [token] chips from all regions in a samples object.
 * Returns [{region, token}] in order of appearance (region order, then text order).
 */
function chipsFromSamples(samples) {
  if (!samples || typeof samples !== "object") return [];
  const out = [];
  for (const [region, text] of Object.entries(samples)) {
    if (typeof text !== "string") continue;
    CHIP_RE.lastIndex = 0;
    let m;
    while ((m = CHIP_RE.exec(text)) !== null) {
      out.push({ region, token: m[1] });
    }
  }
  return out;
}

/**
 * Audit chip → elements coverage across surfaces.
 *
 * @param {Array<{surfaceId: string, layout: object|null}>} surfaces
 *   Surfaces whose layout is null (or whose layout has no samples) are skipped.
 * @returns {{
 *   entries: Array<{surfaceId: string, region: string, token: string, status: "mapped"|"unmapped"}>,
 *   totals: {surfaces: number, tokens: number, mapped: number, unmapped: number}
 * }}
 */
export function auditChips(surfaces) {
  const entries = [];
  let audited = 0;

  for (const { surfaceId, layout } of surfaces) {
    if (!layout) continue;
    const samples = layout.samples;
    const content = layout.content;
    const hasSamples = samples && typeof samples === "object";
    const hasContent = content && typeof content === "object";
    if (!hasSamples && !hasContent) continue;
    audited++;

    // content: path — only ACTIONABLE primitives (btn, tabs) are audited; an
    // actionable element without action: is an unmapped finding. Display-only
    // types (badge, chips, text, …) are exempt by type — no text guessing.
    const contentRegions = new Set(hasContent ? Object.keys(content) : []);
    if (hasContent) {
      walkContent(content, ({ region, el, type }) => {
        if (!type || !CONTENT_TYPES[type]?.actionable) return;
        const status = contentElementHasAction(el) ? "mapped" : "unmapped";
        entries.push({ surfaceId, region, token: contentElementLabel(el, type), status });
      });
    }

    // samples: path — regions covered by content are skipped (content is the
    // source of truth there; their samples line is legacy remainder).
    if (hasSamples) {
      const elements = layout.elements ?? {};
      for (const { region, token } of chipsFromSamples(samples)) {
        if (contentRegions.has(region)) continue;
        const status = Object.prototype.hasOwnProperty.call(elements, token) ? "mapped" : "unmapped";
        entries.push({ surfaceId, region, token, status });
      }
    }
  }

  const mapped = entries.filter((e) => e.status === "mapped").length;
  const unmapped = entries.filter((e) => e.status === "unmapped").length;

  return {
    entries,
    totals: { surfaces: audited, tokens: entries.length, mapped, unmapped },
  };
}

/**
 * Render chip audit results as Markdown.
 * Only surfaces with ≥1 unmapped chip appear in the body.
 * Deterministic sort: surfaceId → region → token (all ascending via localeCompare).
 * No timestamps — output is byte-stable given identical inputs.
 *
 * @param {{ entries: Array, totals: object }} result — from auditChips()
 * @returns {string} Markdown text
 */
export function renderChipAuditMd(result) {
  const { entries, totals } = result;

  let md = `<!-- GENERATED by ui-spec-tools/chip-audit.mjs — DO NOT EDIT BY HAND. Source = surface *.md -->\n\n`;
  md += `# Chip Coverage Audit (generated)\n\n`;
  md += `Surfaces: ${totals.surfaces} · Tokens: ${totals.tokens} · Mapped: ${totals.mapped} · Unmapped: ${totals.unmapped}\n\n`;

  const unmapped = entries
    .filter((e) => e.status === "unmapped")
    .sort(
      (a, b) =>
        a.surfaceId.localeCompare(b.surfaceId) ||
        a.region.localeCompare(b.region) ||
        a.token.localeCompare(b.token)
    );

  if (unmapped.length === 0) {
    md += `All chips mapped — no gaps found.\n`;
    return md;
  }

  md += `## Unmapped Chips\n\n`;
  md += `Each unmapped chip is one of:\n`;
  md += `- **(a) should be mapped** → add to \`elements:\` with the correct action ID\n`;
  md += `- **(b) missing interaction in contract** → add the interaction then map\n`;
  md += `- **(c) legitimately display-only** (badge, placeholder, status chip) → leave unmapped\n\n`;

  // Group by surfaceId (already sorted by localeCompare above)
  const bySurface = new Map();
  for (const e of unmapped) {
    if (!bySurface.has(e.surfaceId)) bySurface.set(e.surfaceId, []);
    bySurface.get(e.surfaceId).push(e);
  }

  for (const surfaceId of [...bySurface.keys()].sort()) {
    const rows = bySurface.get(surfaceId);
    md += `### ${surfaceId}\n\n`;
    md += `| region | token |\n|---|---|\n`;
    for (const { region, token } of rows) {
      md += `| ${region} | \`${token}\` |\n`;
    }
    md += `\n`;
  }

  return md;
}

// ---- CLI ----
// Dynamic imports keep config.mjs / extract.mjs / gray-matter out of the
// top-level module scope so that test imports don't trigger loadConfig().
if (process.argv[1]?.endsWith("chip-audit.mjs")) {
  const [{ SPEC_ROOT }, { listSpecFiles }, { extractLayout }, { default: matter }] =
    await Promise.all([
      import("../config.mjs"),
      import("../extract.mjs"),
      import("./extract-layout.mjs"),
      import("gray-matter"),
    ]);

  const specFiles = listSpecFiles();
  const surfaces = [];

  for (const absPath of specFiles) {
    let raw;
    try {
      raw = readFileSync(absPath, "utf8");
    } catch {
      continue;
    }
    // Extract surfaceId from frontmatter; fall back to filename stem.
    let surfaceId;
    try {
      const fm = matter(raw);
      surfaceId = fm.data?.id ?? basename(absPath, ".md");
    } catch {
      surfaceId = basename(absPath, ".md");
    }

    const layout = extractLayout(raw);
    surfaces.push({ surfaceId, layout });
  }

  const result = auditChips(surfaces);
  const { totals } = result;

  const outDir = join(SPEC_ROOT, "generated");
  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, "chip-audit.md");

  const newContent = renderChipAuditMd(result);
  let existing = "";
  try {
    existing = readFileSync(outPath, "utf8");
  } catch {
    /* first run — file absent */
  }
  if (newContent !== existing) writeFileSync(outPath, newContent, "utf8");

  console.log(
    `✓ chip-audit: ${totals.tokens} tokens · ${totals.mapped} mapped · ${totals.unmapped} unmapped → generated/chip-audit.md`
  );
}
