// Package application — SegmentService: segment CRUD + dynamic rule evaluator.
// Pure domain + ports only; no adapter imports.
//
// SECURITY: RefreshDynamicSegment builds SQL from a WHITELIST of allowed rule
// fields mapped to fixed column names. JSON key names are never interpolated
// into SQL; only parameterised values are passed. Unknown keys → ValidationError.
package application

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/google/uuid"

	"github.com/vantt/data-integration/crm/app/internal/domain"
	"github.com/vantt/data-integration/crm/app/internal/ports"
)

// SegmentService handles segment CRUD and dynamic member refresh.
type SegmentService struct {
	segmentRepo ports.SegmentRepository
	db          sqlQuerier // raw *sql.DB for dynamic queries that can't be pre-generated by sqlc
}

// sqlQuerier is satisfied by *sql.DB — kept minimal to avoid importing the adapter package.
type sqlQuerier interface {
	QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
}

// NewSegmentService constructs a SegmentService.
func NewSegmentService(segmentRepo ports.SegmentRepository, db sqlQuerier) *SegmentService {
	return &SegmentService{segmentRepo: segmentRepo, db: db}
}

// CreateSegment validates and stores a new segment.
func (s *SegmentService) CreateSegment(ctx context.Context, seg *domain.Segment) error {
	if strings.TrimSpace(seg.Name) == "" {
		return domain.NewValidationError("segment name is required")
	}
	if seg.IsDynamic && seg.Definition != "" {
		if err := validateRuleKeys(seg.Definition); err != nil {
			return err
		}
	}
	now := utcNow()
	if seg.SegmentID == "" {
		seg.SegmentID = uuid.New().String()
	}
	seg.CreatedAt = now
	seg.UpdatedAt = now
	return s.segmentRepo.Insert(ctx, seg)
}

// GetSegment returns a segment by ID, or nil if not found.
func (s *SegmentService) GetSegment(ctx context.Context, segmentID string) (*domain.Segment, error) {
	return s.segmentRepo.GetByID(ctx, segmentID)
}

// UpdateSegment persists mutable segment fields.
func (s *SegmentService) UpdateSegment(ctx context.Context, seg *domain.Segment) error {
	if strings.TrimSpace(seg.Name) == "" {
		return domain.NewValidationError("segment name is required")
	}
	if seg.IsDynamic && seg.Definition != "" {
		if err := validateRuleKeys(seg.Definition); err != nil {
			return err
		}
	}
	seg.UpdatedAt = utcNow()
	return s.segmentRepo.Update(ctx, seg)
}

// ListSegments returns all segments.
func (s *SegmentService) ListSegments(ctx context.Context) ([]domain.Segment, error) {
	return s.segmentRepo.List(ctx)
}

// AddMember manually adds a party to a segment (source='manual').
func (s *SegmentService) AddMember(ctx context.Context, segmentID, partyID string) error {
	return s.segmentRepo.UpsertMember(ctx, &domain.SegmentMember{
		SegmentID: segmentID,
		PartyID:   partyID,
		Source:    "manual",
		AddedAt:   utcNow(),
	})
}

// RemoveMember removes a party from a segment.
func (s *SegmentService) RemoveMember(ctx context.Context, segmentID, partyID string) error {
	return s.segmentRepo.DeleteMember(ctx, segmentID, partyID)
}

// ListMembers returns all members of a segment.
func (s *SegmentService) ListMembers(ctx context.Context, segmentID string) ([]domain.SegmentMember, error) {
	return s.segmentRepo.ListMembers(ctx, segmentID)
}

// RefreshDynamicSegment re-evaluates the segment's definition rule and recomputes
// crm_segment_member (source='rule'). Manual members are preserved.
//
// SECURITY INVARIANT: SQL is built from a fixed whitelist of column mappings.
// Rule values are always passed as query parameters — never interpolated.
// Unknown rule keys are rejected with ValidationError before any SQL is built.
//
// GRACEFUL-EMPTY: if cache.wh_customer_insight is absent the query yields zero
// members and returns nil (no error).
func (s *SegmentService) RefreshDynamicSegment(ctx context.Context, segmentID string) (int, error) {
	seg, err := s.segmentRepo.GetByID(ctx, segmentID)
	if err != nil {
		return 0, fmt.Errorf("segment service: refresh: %w", err)
	}
	if seg == nil {
		return 0, domain.NewValidationError(fmt.Sprintf("segment %q not found", segmentID))
	}
	if !seg.IsDynamic {
		return 0, domain.NewValidationError("segment is not dynamic; use manual member management")
	}
	if strings.TrimSpace(seg.Definition) == "" {
		return 0, domain.NewValidationError("dynamic segment has no rule definition")
	}

	rule, err := parseAndValidateRule(seg.Definition)
	if err != nil {
		return 0, err
	}

	partyIDs, err := s.evaluateRule(ctx, rule)
	if err != nil {
		return 0, fmt.Errorf("segment service: evaluate rule: %w", err)
	}

	// Purge stale rule-sourced members, then insert fresh set.
	if err := s.segmentRepo.DeleteRuleMembers(ctx, segmentID); err != nil {
		return 0, fmt.Errorf("segment service: purge rule members: %w", err)
	}
	now := utcNow()
	for _, pid := range partyIDs {
		if err := s.segmentRepo.UpsertMember(ctx, &domain.SegmentMember{
			SegmentID: segmentID,
			PartyID:   pid,
			Source:    "rule",
			AddedAt:   now,
		}); err != nil {
			return 0, fmt.Errorf("segment service: upsert member %s: %w", pid, err)
		}
	}
	return len(partyIDs), nil
}

// ─── rule parsing & evaluation ────────────────────────────────────────────────

// validateRuleKeys decodes the definition JSON and rejects any unknown key.
// This is the security boundary: only whitelisted keys may appear.
func validateRuleKeys(definition string) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal([]byte(definition), &raw); err != nil {
		return domain.NewValidationError(fmt.Sprintf("segment definition is not valid JSON: %v", err))
	}
	for k := range raw {
		if _, ok := domain.AllowedRuleKeys[k]; !ok {
			return domain.NewValidationError(
				fmt.Sprintf("unknown segment rule key %q — allowed: %s",
					k, allowedKeyList()),
			)
		}
	}
	return nil
}

func parseAndValidateRule(definition string) (*domain.SegmentRule, error) {
	if err := validateRuleKeys(definition); err != nil {
		return nil, err
	}
	var rule domain.SegmentRule
	if err := json.Unmarshal([]byte(definition), &rule); err != nil {
		return nil, domain.NewValidationError(fmt.Sprintf("cannot parse segment rule: %v", err))
	}
	return &rule, nil
}

// evaluateRule translates a validated SegmentRule into a parameterized SQL query
// and returns matching party_ids.
//
// Dispatches to:
//   - buildQueryWithHaving when days_since_last_order_gte is set (requires GROUP BY + HAVING
//     because the elapsed-days expression uses MAX aggregate over wh_order_hdr).
//   - buildQueryNoHaving for all insight-only rules (value_group, customer_status,
//     channel_preference) — simpler WHERE-only query against wh_customer_insight.
//
// SECURITY: every clause uses a fixed column reference + a '?' placeholder.
// The rule struct fields (not the raw JSON map keys) drive the WHERE clauses.
func (s *SegmentService) evaluateRule(ctx context.Context, rule *domain.SegmentRule) ([]string, error) {
	needsInsight := len(rule.ValueGroup) > 0 || rule.CustomerStatus != "" || rule.ChannelPreference != ""
	needsOrders := rule.DaysSinceLastOrderGte > 0

	var query string
	var args []any
	if needsOrders {
		// days_since_last_order_gte requires GROUP BY + HAVING (MAX aggregate).
		query, args = buildQueryWithHaving(rule, needsInsight)
	} else {
		// Insight-only rules: simple WHERE query, no aggregation.
		query, args = buildQueryNoHaving(rule, needsInsight)
	}

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		if isCacheMissingTable(err) {
			// cache tables not yet populated — return empty (graceful-empty).
			return []string{}, nil
		}
		return nil, fmt.Errorf("evaluate rule: %w", err)
	}
	defer rows.Close()

	var partyIDs []string
	for rows.Next() {
		var pid string
		if err := rows.Scan(&pid); err != nil {
			return nil, fmt.Errorf("evaluate rule: scan: %w", err)
		}
		partyIDs = append(partyIDs, pid)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("evaluate rule: rows: %w", err)
	}
	return partyIDs, nil
}

// buildQueryNoHaving produces a simple WHERE-only query for insight-only rules
// (value_group, customer_status, channel_preference). No aggregation needed.
// All values are parameterized.
func buildQueryNoHaving(rule *domain.SegmentRule, needsInsight bool) (string, []any) {
	var whereClauses []string
	var args []any

	if len(rule.ValueGroup) > 0 {
		placeholders := make([]string, len(rule.ValueGroup))
		for i, v := range rule.ValueGroup {
			placeholders[i] = "?"
			args = append(args, v)
		}
		whereClauses = append(whereClauses, fmt.Sprintf("ci.value_group IN (%s)", strings.Join(placeholders, ",")))
	}
	if rule.CustomerStatus != "" {
		whereClauses = append(whereClauses, "ci.customer_status = ?")
		args = append(args, rule.CustomerStatus)
	}
	if rule.ChannelPreference != "" {
		whereClauses = append(whereClauses, "ci.channel_preference = ?")
		args = append(args, rule.ChannelPreference)
	}

	var sb strings.Builder
	sb.WriteString(`
		SELECT DISTINCT p.party_id
		FROM crm_party p`)

	if needsInsight {
		sb.WriteString(`
		LEFT JOIN crm_party_identity pi2
			ON pi2.party_id = p.party_id AND pi2.identity_type = 'sapo_customer'
		LEFT JOIN cache.wh_customer_insight ci
			ON ci.customer_id = CAST(pi2.identity_value AS INTEGER)`)
	}

	sb.WriteString(`
		WHERE p.is_merged = 0 AND p.status = 'active'`)

	if len(whereClauses) > 0 {
		sb.WriteString(" AND ")
		sb.WriteString(strings.Join(whereClauses, " AND "))
	}

	return sb.String(), args
}

// buildQueryWithHaving produces a clean GROUP BY + HAVING query when
// days_since_last_order_gte is present. All values are parameterized.
//
// REACTIVATION SEMANTIC (intentional, do not change):
// This query only matches parties who HAVE at least one order with date_key matching
// the elapsed-days condition. Parties with NO orders in wh_order_hdr are excluded
// by the HAVING clause (MAX(oh.date_key) IS NULL → julianday expression returns NULL →
// NULL >= threshold is false). This is correct: parties with no orders are acquisition
// targets, not reactivation candidates.
func buildQueryWithHaving(rule *domain.SegmentRule, needsInsight bool) (string, []any) {
	var whereClauses []string
	var havingClauses []string
	var args []any

	if len(rule.ValueGroup) > 0 {
		placeholders := make([]string, len(rule.ValueGroup))
		for i, v := range rule.ValueGroup {
			placeholders[i] = "?"
			args = append(args, v)
		}
		whereClauses = append(whereClauses, fmt.Sprintf("ci.value_group IN (%s)", strings.Join(placeholders, ",")))
	}
	if rule.CustomerStatus != "" {
		whereClauses = append(whereClauses, "ci.customer_status = ?")
		args = append(args, rule.CustomerStatus)
	}
	if rule.ChannelPreference != "" {
		whereClauses = append(whereClauses, "ci.channel_preference = ?")
		args = append(args, rule.ChannelPreference)
	}

	// days_since_last_order_gte goes into HAVING because it uses MAX aggregate.
	havingClauses = append(havingClauses, `(julianday('now') - julianday(
		substr(CAST(MAX(oh.date_key) AS TEXT), 1, 4) || '-' ||
		substr(CAST(MAX(oh.date_key) AS TEXT), 5, 2) || '-' ||
		substr(CAST(MAX(oh.date_key) AS TEXT), 7, 2)
	)) >= ?`)
	args = append(args, rule.DaysSinceLastOrderGte)

	var sb strings.Builder
	sb.WriteString(`
		SELECT p.party_id
		FROM crm_party p
		LEFT JOIN crm_party_identity pi2
			ON pi2.party_id = p.party_id AND pi2.identity_type = 'sapo_customer'`)

	if needsInsight {
		sb.WriteString(`
		LEFT JOIN cache.wh_customer_insight ci
			ON ci.customer_id = CAST(pi2.identity_value AS INTEGER)`)
	}

	sb.WriteString(`
		LEFT JOIN cache.wh_order_hdr oh
			ON oh.customer_id = CAST(pi2.identity_value AS INTEGER)
		WHERE p.is_merged = 0 AND p.status = 'active'`)

	if len(whereClauses) > 0 {
		sb.WriteString(" AND ")
		sb.WriteString(strings.Join(whereClauses, " AND "))
	}

	sb.WriteString(" GROUP BY p.party_id")

	if len(havingClauses) > 0 {
		sb.WriteString(" HAVING ")
		sb.WriteString(strings.Join(havingClauses, " AND "))
	}

	return sb.String(), args
}

// allowedKeyList returns a comma-separated sorted list of allowed rule keys for error messages.
func allowedKeyList() string {
	keys := make([]string, 0, len(domain.AllowedRuleKeys))
	for k := range domain.AllowedRuleKeys {
		keys = append(keys, k)
	}
	return strings.Join(keys, ", ")
}
